### ISSUE TITLE
doesnt work with homebrew python

### ISSUE THREAD

**Issue by catesandrew** [mailmate/asciimath.mmbundle#1]
fix is easy

``` bash
#!/usr/bin/env python
```

vs

```
#!/usr/bin/python
```

**Comment by catesandrew** [comment]
although that fixes the script from crashing at the prompt, still not fixing the issue.

**Comment by freron** [comment]
If it's not fixed then why did you close this issue?

I tried installing with `brew install python` and the bundle appears to still be working for me. Also if I don't change the shebang.

(There is a known bug triggered when having more than 1 math segment of the same type. This is a bug in MailMate itself and fixed for the next update.)

**Comment by catesandrew** [comment]
so for me the fix was a bit complicated. i had to install pip into my /usr/bin directory where the /usr/bin/python was located. i ended up having to set my PATH to just whats found in `/etc/paths` basically and install `pip` as well as pip install `asciimathml`. I had to get rid of the link to /usr/local/bin/python to make it work.

``` bash
PATH=/usr/bin:/bin:/usr/sbin:/sbin sudo -u root -H easy_install pip
PATH=/usr/bin:/bin:/usr/sbin:/sbin sudo -u root -H pip install asciimathml
```

I eventually was able to get asciimathml installed into the `/Library/Python/2.7/site-packages/` folder and got it to work. When it was installed under brew path of `/usr/local/lib/python2.7/site-packages/` it wasn't able to import the asciimathml correctly. Tricky but it eventually came to work, and this isn't a mailmate bug so closed it

**Comment by freron** [comment]
Ok. Ideally, the bundle should offer to install `asciimathml` if it's not available, but this is problematic if it's not installed in the correct location using `easy_install`. I can see that the `easy_install` command does take an `--install-dir` argument. That might be helpful.
